server:
  port: 51802

# swagger-ui custom path
#springdoc:
#  swagger-ui:
#  path: /swagger-ui.html

# 是否启用（默认启用，生产可配置false关闭）
#springdoc:
#  swagger-ui:
##    enabled: true
#    path: /swagger-ui.html

#springdoc:
#  api-docs:
#    enabled: true
##    path: /你自己的项目名称.html
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: on
